2025-02-08 15:09:57,842 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 15:15:47,100 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 15:19:01,704 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 15:21:20,145 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 15:25:12,456 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 15:31:51,137 - __main__ - ERROR - Error during OCR processing: Unable to load weights from pytorch checkpoint file for 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin' at 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
2025-02-08 15:50:06,206 - __main__ - ERROR - Error during OCR processing: Unable to load weights from pytorch checkpoint file for 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin' at 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
2025-02-08 15:53:00,886 - __main__ - ERROR - Error during OCR processing: 
TFVisionEncoderDecoderModel requires the TensorFlow library but it was not found in your environment.
However, we were able to find a PyTorch installation. PyTorch classes do not begin
with "TF", but are otherwise identically named to our TF classes.
If you want to use PyTorch, please use those classes instead!

If you really do want to use TensorFlow, please follow the instructions on the
installation page https://www.tensorflow.org/install that match your environment.

2025-02-08 16:07:21,336 - __main__ - ERROR - Error during OCR processing: Failed to import transformers.models.vision_encoder_decoder.modeling_tf_vision_encoder_decoder because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.
2025-02-08 16:11:29,245 - __main__ - ERROR - Error during OCR processing: naver-clova-ix/donut-base-finetuned-cord-v2 does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.
2025-02-08 16:15:01,265 - __main__ - ERROR - Error during OCR processing: Unable to load weights from pytorch checkpoint file for 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin' at 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
2025-02-08 16:25:42,426 - __main__ - ERROR - Error during OCR processing: Unable to load weights from pytorch checkpoint file for 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin' at 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
2025-02-08 16:36:31,477 - __main__ - ERROR - Error during OCR processing: Unable to load weights from pytorch checkpoint file for 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin' at 'C:\Users\asus\.cache\huggingface\hub\models--naver-clova-ix--donut-base-finetuned-cord-v2\snapshots\8003d433113256b4ce3a0f5bf604b29ff78a7451\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
2025-02-08 16:47:53,704 - __main__ - ERROR - Error during OCR processing: __init__() got an unexpected keyword argument 'from_pt'
2025-02-08 16:51:02,168 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
2025-02-08 16:52:22,409 - __main__ - ERROR - Error during OCR processing: __init__() got an unexpected keyword argument 'padding'
2025-02-08 16:53:30,530 - __main__ - ERROR - Error during OCR processing: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.
